### ISSUE TITLE
Update jQuery to 2.2.x

### ISSUE THREAD

**Issue by croqaz** [libxmljs/libxmljs-dom#3]
Hi.

I made a custom jQuery build on "2.2-stable" branch with:
> grunt custom:-ajax,-css,-deprecated

I tested the jQuery-v2.2.4 build, in "lib/jquery.js" and everything works.

I want to make a PR and submit this update, is that OK ?

I want to use this library, but it needs a bit of love :)

**Comment by rchipka** [comment]
Yes, I would accept a pull request for that.

Contributions to this project are always welcome.
